import { ENV_VAR_PREFIX } from './ENV_VAR_PREFIX';

export const BATTLENET = {
  region: `${ENV_VAR_PREFIX}_BATTLENET_REGION`,
  clientId: `${ENV_VAR_PREFIX}_BATTLENET_CLIENT_ID`,
  clientSecret: `${ENV_VAR_PREFIX}_BATTLENET_CLIENT_SECRET`,
};
